server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://hiringdaydb.ckqem7tcynv0.eu-west-3.rds.amazonaws.com:5432/hiringdaydb
    username: decagon
    password: decagonhq

  jpa:
    hibernate:
      ddl-auto: update