#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/hire_day_db
#    username: postgres
#    password: 250790
#
#  jpa:
#    hibernate:
#      ddl-auto: update
# hireday.ciscs8rmbsvf.eu-west-3.rds.amazonaws.com
server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://hireday.ciscs8rmbsvf.eu-west-3.rds.amazonaws.com:5432/hiredaydb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

#server:
#  port: 5000
#
#spring:
#  datasource:
#    url: jdbc:postgresql://hiringdaydb.ckqem7tcynv0.eu-west-3.rds.amazonaws.com:5432/hiringdaydb
#    username: decagon
#    password: decagonhq
#
#  jpa:
#    hibernate:
#      ddl-auto: update